services:
  - type: web
    name: alliance-discord-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: TEST_GUILD_ID
        sync: false
      - key: MONGO_URI
        sync: false
      - key: PHOENIX_REBELS_ROLE_ID
        sync: false
      - key: TRASH_COLLECTORS_ROLE_ID
        sync: false
      - key: REQUIRED_ROLE_ID
        sync: false
      - key: PREFIX
        value: "!"
      - key: EMBED_COLOR
        value: "#0099ff"
      - key: CALLER_FEE_RATE
        value: "0.08"
